name: Create File

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create file
        run: |
          touch sample.txt
          pwd
          ls -la

      - name: Display file
        run: |
          pwd
          ls -la
          cat sample.txt
