name: Create File

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create a file
        run: |
          echo "Hello, GitHub Actions!" > sample.txt
          echo "This file was created on $(date)" >> sample.txt

      - name: Display file content
        run: cat sample.txt.
